### ISSUE TITLE
missing mappedBy and null childs with OneToMany association

### ISSUE THREAD

**Issue by anz000** [kaiso/relmongo#43]
I'll take the example you have posted in the wiki: (Person and Cars)

```
class Person{
...
@OneToMany(fetch= FetchType.LAZY, cascade = CascadeType.ALL)
@JoinProperty(name="cars")
private List<Car> cars = new ArrayList<>();

public addCar(Car c){
car.setPerson(this);
this.getCars().add(car);
}
}
```

```
class Cars{
...
@ManyToOne(mappedBy = "cars", fetch= FetchType.EAGER)
private Person owner;
}
```

```
Person p = new Person();
Car c = new Car();
p.addCar(car)
p.save();

//saving the 2nd car overrides the 1st car values
Car car2 = new Car();
p.add(car2);
p.save();
```

I've seen instances where saving `car2` creates `null` (default values) of the class. Am I doing something wrong?

Apparently, when `this.getCars()` is called it loads the first car with the correct id but all of the other properties are empty/class defaults (and not the saved value).

**Comment by anz000** [comment]
I think there might a missing `mappedBy` on a `@OneToMany`.

**Comment by kaiso** [comment]
Regarding the fact that there are no `mappedBy` in the `@OneToMany` it is a choice for performance and convenience, by using the annotation properly they achieve the two way relationship very well.

Regarding your problem, the absence of the car in the second call of save is due that after the first call you have not loaded the `Person`entity so RelMongo can not see the Id affected by `MongoDB`so in order to work in your example you should load the person before editing it or add the car list directly and do one save. like below :
```
        Car car1 = new Car();
        Car car2 = new Car();
       
        Person person = new Person();
        person.setCars(Arrays.asList(new Car[] { car1, car2 }));
        repository.save(person);
```

**Comment by anz000** [comment]
My bad .. there was a typo in the code while adding the second car.

```
Person p = new Person();
p.setId(1);
Car c = new Car();
p.addCar(car)
p.save();

// Now after "x" time later
Person p = getPersonById(1);
Car car2 = new Car();
p.getCars().add(car2);
p.save();
```
I was having problem with nulls for the first car values when trying to save the second car.

My expectation was `p.getCars()` should get all the existing cars, and add a new `car2` when I call `add()` and link it to the person. I have some properties of car that cannot be null. Even if null could be accepted, it would end up overwriting the the car1 values. 

I also realized that the `audit modified  date` on car1 also changes, is it possible to just add car2 without changing car1 at all? I think there is a `$set` in MongoDB to allow to add to an existing array without changing the previous values.

Also, is it necessary to do `car2.setPerson(p)` before saving `p.save()`?

**Comment by kaiso** [comment]
The behaviour is that the children will change when you update the parent, but it keeps the Ids, cascading changes means cascading operations so updating person will update cars and that is the desired behavior of the framework.

Regarding the second question it is not necessary unless you want to use the person entity for some logic and saving it later so like `Java Persistence API` you should set the both sides of the relation for convenience and coherance.

Since it is not a bug I will close the isse, If you have other questions please post them in the gitter channel.
